# Generated by Django 4.0.3 on 2022-11-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_artticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='artticle',
            new_name='article',
        ),
    ]
