# Generated by Django 4.0.3 on 2022-11-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagarc',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='tagarc',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scopes', to='articles.tag'),
        ),
    ]
